name: Tanzania Explorer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47555
title: '- we show you Africa...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0072a7'
    - '#242b2c'
    - '#e1e1e1'
    - '#62af6c'
    - '#ffff00'
  brandStrength: 0.8128974309656769
  lightness: 0.08961566281504929
  saturation: 0.75
  rhythmicContrast: 0.7904803305864334
purpose: []
